packages:
- '.'
- location:
    git: https://github.com/ku-fpg/hermit
    commit: d38052f3ec4cdbcc3ed4df308dae5588354c5be7
  extra-dep: true
- location:
    git: https://github.com/ku-fpg/netlist
    commit: 9869fe5eca7b0478bb352d2f14b2d46a01e46938
  extra-dep: true
  subdirs:
  - netlist
  - verilog
  - netlist-to-verilog
- location:
    git: https://github.com/conal/circat
    commit: 19800ccc6b675b0b6f48a7c59c8e8d37692d0d74
  extra-dep: true
- location:
    git: https://github.com/conal/shaped-types
    commit: 213e08be9cddadb4c7cab4c181fad3adc4b981da
  extra-dep: true
resolver: nightly-2016-07-18
extra-deps:
- ty-0.1.7
- newtype-generics-0.4
- kure-2.16.12
- marked-pretty-1.1.2.1
