flags: {}
packages:
- '.'
- ../circat
- ../shaped-types
- location:
    git: https://github.com/ku-fpg/hermit
    commit: d38052f3ec4cdbcc3ed4df308dae5588354c5be7
  extra-dep: true
- location:
    git: https://github.com/ku-fpg/netlist
    commit: 9869fe5eca7b0478bb352d2f14b2d46a01e46938
  subdirs:
  - netlist
  - verilog
  - netlist-to-verilog
  extra-dep: true
extra-deps:
- applicative-numbers-0.1.3
- kure-2.16.12
- marked-pretty-1.1.2.1
- newtype-generics-0.4
- ty-0.1.7
resolver: nightly-2016-07-18
